name: CI Build

on:
  workflow_dispatch:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build - ${{ matrix.os }}(${{ matrix.configuration }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        configuration: ['Debug']

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.400

    - name: Install workload
      run: dotnet workload install maui

    - name: Setup Java SDK
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build
      run: dotnet build -c ${{ matrix.configuration }}
